name: Deploy para InfinityFree

on:
  push:
    branches: [ "main" ] # Troque por "master" se for o nome da sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Enviar arquivos via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: $ {{ secrets.FTP_SERVER }}
          username: $ {{ secrets.FTP_USERNAME }}
          password: $ {{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./htdocs/ 
          ftp-passive: true