name: Deploy para InfinityFree

on:
  push:
    branches:
      - main # Troque por "master" se for o nome da sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Enviar arquivos via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.3
        with:
          server: ftpupload.net
          username: if0_37138573
          password: $ {{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: htdocs/ 